//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace windows_programing_curriculum_design
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database2Entities2 : DbContext
    {
        public Database2Entities2()
            : base("name=Database2Entities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Repair> Repair { get; set; }
        public virtual DbSet<Room> Room { get; set; }
        public virtual DbSet<RootPassword> RootPassword { get; set; }
        public virtual DbSet<StudentTable> StudentTable { get; set; }
        public virtual DbSet<Transfe> Transfe { get; set; }
        public virtual DbSet<yyy> yyy { get; set; }
    }
}
